SELECT *
FROM public.customer_shopping_behavior
LIMIT 20;
--Q1. what is the total revenue generated by male vs. female customers?
select "Gender",
sum ("Purchase Amount (USD)") as revenue
from customer_shopping_behavior
group by "Gender";

--Q2. Which customers used a discount but still spent more than the average purchase amount?
Select"Customer ID", "Purchase Amount (USD)"
from customer_shopping_behavior
where "Discount Applied" = 'Yes'
  and "Purchase Amount (USD)" >
      (select AVG("Purchase Amount (USD)")
       from customer_shopping_behavior);
--Q3. Which are the top 5 products with the highest average review rating?
select "Item Purchased", 
       ROUND(AVG("Review Rating"::numeric), 2) as "Average Product Rating"
from customer_shopping_behavior
group by "Item Purchased"
order by avg("Review Rating") desc
limit 5;

--Q4. compare the average purchase amount between standard and Express Shipping.
select "Shipping Type",
       ROUND(AVG("Purchase Amount (USD)"),2)
from customer_shopping_behavior
where "Shipping Type" in ('Standard','Express')
group by "Shipping Type"


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select "Subscription Status",
count ("Customer ID") as total_Customers,
       ROUND(AVG("Purchase Amount (USD)"),2) as avg_spend,
	   ROUND(sum("Purchase Amount (USD)"),2) as total_revenue
	   from customer_shopping_behavior
	   group by "Subscription Status"
	   order by total_revenue, avg_spend desc;
--Q6. Which 5 product have the highest percantage of purchase with discounts applied?
SELECT "Item Purchased",
       ROUND(
           100.0 * SUM(
               CASE
                   WHEN "Discount Applied" = 'Yes' THEN 1
                   ELSE 0
               END
           ) / COUNT(*),
           2
       ) AS discount_rate
FROM customer_shopping_behavior
GROUP BY "Item Purchased"
ORDER BY discount_rate DESC
LIMIT 5;

--Q7. Segement customers into new, Returning, and lLoyal based on their total
--number of previous purchases, and show the count of each segemnt.
WITH customer_type AS (
    SELECT
        "Customer ID",
        "Previous Purchases",
        CASE
            WHEN "Previous Purchases" = 1 THEN 'New'
            WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS "Customer Segment"
    FROM customer_shopping_behavior
)

SELECT
    "Customer Segment",
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY "Customer Segment";

--Q8. What are the top 3 most purchase products within each category?
with item_counts as (
select"Category",
"Item Purchased",
count("Customer ID") AS total_orders,
Row_number() over(partition by "Category" order by count("Customer ID") DESC) as item_rank
 FROM customer_shopping_behavior
 group by "Category", "Item Purchased"
)
select item_rank,"Category","Item Purchased",total_orders 
from item_counts
where item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select "Subscription Status",
count ("Customer ID") as repeat_buyers
from customer_shopping_behavior
where "Previous Purchases" > 5
group by "Subscription Status"

--Q10. what is the revenue contribution of each age group?
select "Age",
sum ("Purchase Amount (USD)") as total_revenue
from customer_shopping_behavior
group by "Age"
order by total_revenue desc;

SELECT current_database();